name: Release Dev Version
on:
  workflow_dispatch:
    inputs:
      confirm_prs_resolved:
        description: "I have made sure all PRs are resolved"
        required: true
        type: boolean
      confirm_branch:
        description: "I have set this workflow to run from the beta branch"
        required: true
        type: boolean
      new_version:
        description: "The new beta version number"
        required: true
        type: number
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Fetch full gh-pages and stable branches and create user
        run: |
          git fetch origin gh-pages --depth=1
          git fetch origin stable --depth=1
          git config user.name ci-bot
          git config user.email ci-bot@example.com
      - name: Get version numbers
        run: |
          echo "beta_version=$(mike list beta | awk -F'[()]' '{print $2}')" >> $GITHUB_ENV
          echo "stable_version=$(mike list stable | awk -F'[()]' '{print $2}')" >> $GITHUB_ENV
      - name: Rename the current stable version to its version number
        run: |
          mike retitle -p ${{ env.stable_version }} ${{ env.stable_version }}
      - name: Deploy current beta version as stable
        run: |
          mike deploy -p -u ${{ env.beta_version }} stable -t stable
      - name: Deploy copy of beta with incremented version number for development
        run: |
          mike deploy -p -u ${{ inputs.new_version }} beta -t beta
      - name: Merge beta branch with stable
        run: |
          git checkout stable
          git pull
          git merge beta -m "Releasing Beta Version"
          git push
